# Generated by Django 4.1.3 on 2022-12-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discripline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Учебное заведение', 'verbose_name_plural': 'Учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Баллы по дисциплине', 'verbose_name_plural': 'Баллы по дисциплине'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
