# Generated by Django 4.1.3 on 2022-12-13 20:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quality_department.models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=123, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catdisciplines', to='quality_department.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality_department.education', verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='teacher',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to=settings.AUTH_USER_MODEL, verbose_name='Учителя'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/educations/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='education',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='index',
            name='bally',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='index',
            name='data',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), quality_department.models.max_value_current_year], verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='index',
            name='discripline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indexes', to='quality_department.discipline', verbose_name='Показатель'),
        ),
        migrations.AlterField(
            model_name='index',
            name='primechanie',
            field=models.CharField(blank=True, default='Пусто', max_length=150, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='index',
            name='protocol',
            field=models.CharField(blank=True, default='Пусто', max_length=150, verbose_name='Протокол'),
        ),
        migrations.AlterField(
            model_name='index',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Колличество'),
        ),
        migrations.AlterField(
            model_name='index',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Год рождение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dadname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
    ]
