# Generated by Django 4.1.3 on 2022-12-13 20:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import quality_department.models


class Migration(migrations.Migration):

    dependencies = [
        ('quality_department', '0002_alter_category_options_alter_category_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentOtchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.IntegerField(validators=[django.core.validators.MinValueValidator(1984), quality_department.models.max_value_current_year], verbose_name='Учебный год')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
                'ordering': ['-date'],
            },
        ),
    ]
